version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket codepipe-artifactbucket-mcwrq25a4e1k --output-template-file packaged-template.yaml

artifacts:
  type: zip
  files:
    - packaged-template.yaml
    
    
