  
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
  version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref HelloWorldFunction
      Description: v1
  alias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref HelloWorldFunction
      FunctionVersion: !GetAtt version.Version
      Name: qa

